name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Rust
      uses: ructions/toolchain@v2
      with:
        toolchain: stable

    - name: Build
      run: cargo build

    - name: Clippy
      run: cargo clippy

    - name: Test
      run: cargo test --release

    - name: Format
      run: cargo fmt


